server.port=${PORT:5000}
spring.application.name=urlShortener

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/urlshortener}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

app.baseUrl=${APP_BASE_URL:http://localhost:5000}
